#!/bin/bash

#****************************************************
#
#           script permettant de generer des fichiers
#           de conditions initiales a partir d'un
#           fichier .txt lisible par un humain
#
#           Le fichier .txt doit contenir tous les
#           elements du fichier de conditions initiales
#           dans l'ordre. Mais il peut aussi contenir des
#           sauts de ligne, des lignes blanches et des 
#           commentaires commencant par le caractere '#'
#
# usage:
#      txt2dat NOMFICHIER.txt
#
#      generera le fichier NOMFICHIER.dat
#
#
# Derniere revision: 17/12/2015
# G. BOUE
#****************************************************


################################
# error message
################################
function error() {
  echo ""
  echo "txt2dat permet de generer un fichier de conditions initiales"
  echo "pour le programme intcircumbinmaree.x a partir d'un fichier"
  echo "xxx.txt lisible par un humain"
  echo ""
  echo "usage:"
  echo "     txt2dat [-h] xxx.txt"
  echo ""
  echo "  -h, --h, -help, --help : affiche cette aide et sort"
  echo "  xxx.txt                : fichier de conditions initiales lisible par un humain"
  echo ""
  exit 1
}

################################
# default parameters
################################
txt="FICHIER_NON_RENSEIGNE.txt"
dat=

##################################################################
# genere un fichier ou le nombre de colonnes est egal a "a+b*npla"
##################################################################
a=12   # chaine + npla + m0 + typeci + (Rpla,xi,k20,taue,tau2) + om[1:3]
b=7    # mpla + coord_ci[1:6]

################################
# read command line
################################
while [ $# -gt 0 ]; do
  case "$1" in
    -h | --h | -help | --help )
      error
      ;;
    * )
      txt="$1"
      dat=${txt%.*}.dat
      shift
      ;;
  esac
done

#################################
# check file
#################################
if [[ -f "$txt" ]]; then
  # print comment on the terminal
  echo "lecture du fichier \"$txt\""
  echo "creation du fichier \"$dat\""
else
  error
fi

#################################
# do the job
#################################
sed -e 's/#/\n#/g' $txt | gawk '$0!~/#/' | xargs -n 1 | gawk -v a=$a -v b=$b 'BEGIN {l=0;lm=0;s=""} l==lm-1 && l>1 {print s,$1; l=0; lm=0} l>1 && l<lm {s=s" "$1;l++} l==1 {lm=a+b*$1; s=s" "$1; l++} l==0 && s=="" {s=$1; lm=0; l++} l==0 && s!="" {s=""}' > $dat
